yaml:
 str: 字符串可以不加引号
 specialStr: "双引号直接输出\n特殊字符"
 specialStr2: '单引号可以转义\n特殊字符'
 flag: false
 num: 666
 dNum: 88.88
 txtarray: 1,2,3,a 
 list:
  - one
  - two
  - two
 set: [1,2,2,3]
 map: {k1: v1, k2: v2}
 positions:
 #-后的属性必须有1个空格
  - 
    name: ITDragon
    salary: 15000.00
  - 
    name: ITDragonBlog
    salary: 18888.88
ran: # 这里的prefix不能是random，
 ran-value: ${random.value}
 ran-int: ${random.int}
 ran-long: ${random.long}
 ran-int-num: ${random.int(10)}
 ran-int-range: ${random.int[10,20]}
 ran-placeholder: placeholder_${ran.ran-value:此处不能有空格，且key为完整路径}
itdragon:
 nick-name: ITDragonBlog
 email: 1234567890@qq.com
 iphone: 1234567890
 abilities: [java, sql, html]
 created_date: 2018/03/31 15:27:30