spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.70.66.100:1521:newkiiik
    username: yw_qh_kh
    password: bms_yw_qh
