server:
  port: 80
security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti5?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

#mybatis config
mybatis:
  mapper-locations: classpath:/mapper/*.xml