server:
  port: 3002
spring:
  application:
    name: demo-1
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@localhost:8888/eureka/
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
        appname: demo-1

